### PR TITLE
fix: expose serialization to red proxies

### PR DESCRIPTION
**Pull request by jdalton**
fix: expose serialization to red proxies

### CODE REVIEW

**Review by rwaldron — APPROVED** [review]
🥳

**Comment by rwaldron** [comment]
I've tested this in locker via local link and it resolves the postMessage test failures. One step closer to multi-window!

**Comment by jdalton** [comment]
I'm going to try a variation of this that's simpler that I think may still do it.

**Comment by jdalton** [comment]
Closing in favor of #344.

**Pull request closed without merging**
