### PR TITLE
fix: transpile syntax to baseline support @W-10081191@

### PR DESCRIPTION
**Pull request by jdalton**
transpile syntax to baseline support

### CODE REVIEW

**Review by manuel-jasso — COMMENTED** [review]
What's an example of the transform?

**Comment by jdalton** [comment]
Transforming things like optional chaining which isn't supported in Android emulator.

**Comment by rwaldron** [comment]
Optional chaining is only used once, and I think  we could probably just not use it if that's easier.

**Comment by jdalton** [comment]
> Optional chaining is only used once, and I think we could probably just not use it if that's easier.

We've tried avoiding syntax before and we (I) forget again. Having it covered by our tools will let us be free 🙌

**Review by arcadeteddy — APPROVED** [review]

**Review by garychangsf — APPROVED** [review]

**Pull request merged**
