### PR TITLE
feat: flag a descriptor as foreign in more cases

### PR DESCRIPTION
**Pull request by jdalton**
feat: flag a descriptor as foreign in more cases

### CODE REVIEW

**Comment by rwaldron** [comment]
Needs to be re-opened from a branch on https://github.com/salesforce/near-membrane, otherwise CI wont run (because this repo is public)

**Comment by jdalton** [comment]
@garychangsf Something has changed and CI is no longer allowing pull requests from forks _(the way it should be - says old man shaking fist at clouds)_ to be CI-run.

**Comment by jdalton** [comment]
Oof. Is this because of that sec stuff. There used to be mitigations for that stuff on other providers. But OKAY just because security :P

**Comment by jdalton** [comment]
Moved to #368

**Pull request closed without merging**
